export interface Property {
  id: string;
  title: string;
  location: string;
  area: number;
  price: number;
  type: "terreno" | "imovel";
  description: string;
  features: string[];
  images: string[];
  coordinates: { x: number; y: number };
  contact: string;
  availability: boolean;
  featured?: boolean;
}

export const properties: Property[] = [
  // Quadra A - Imóveis de Alto Padrão (Frente)
  {
    id: "1",
    featured: true,
    title: "Mansão Capitale",
    location: "Petrolina - Orla",
    area: 1200,
    price: 4500000,
    type: "imovel",
    description: "Espetacular mansão de frente para o rio, com acabamento de luxo, piscina com borda infinita e área gourmet completa.",
    features: ["Vista Rio", "Piscina Infinita", "5 Suítes", "Automação"],
    images: ["https://picsum.photos/seed/p1/800/600", "https://picsum.photos/seed/p1b/800/600"],
    coordinates: { x: 28, y: 19.6 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "2",
    title: "Casa Contemporânea",
    location: "Petrolina - Centro",
    area: 800,
    price: 3200000,
    type: "imovel",
    description: "Casa com arquitetura moderna, pé direito duplo e integração total entre ambientes.",
    features: ["Pé direito duplo", "Energia Solar", "4 Suítes"],
    images: ["https://picsum.photos/seed/p2/800/600", "https://picsum.photos/seed/p2b/800/600"],
    coordinates: { x: 31.7, y: 19.5 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "3",
    title: "Lote Comercial Premium",
    location: "Petrolina",
    area: 1000,
    price: 1800000,
    type: "terreno",
    description: "Lote estrategicamente localizado na avenida principal, ideal para comércio ou clínica.",
    features: ["Comercial", "Avenida Principal", "Plano"],
    images: ["https://picsum.photos/seed/p3/800/600"],
    coordinates: { x: 35.4, y: 19.4 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "4",
    title: "Sobrado Neoclássico",
    location: "Petrolina",
    area: 800,
    price: 2900000,
    type: "imovel",
    description: "Sobrado imponente com estilo neoclássico, jardins paisagísticos e acabamento em mármore.",
    features: ["Estilo Neoclássico", "Jardim", "Escritório"],
    images: ["https://picsum.photos/seed/p4/800/600"],
    coordinates: { x: 39.1, y: 19.4 },
    contact: "contato@capitale.com",
    availability: false,
  },
  {
    id: "5",
    title: "Terreno de Esquina",
    location: "Petrolina",
    area: 950,
    price: 980000,
    type: "terreno",
    description: "Amplo terreno de esquina, excelente ventilação e posição solar.",
    features: ["Esquina", "Nascente", "Bem localizado"],
    images: ["https://picsum.photos/seed/p5/800/600"],
    coordinates: { x: 42.8, y: 19.4 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "6",
    title: "Casa Térrea Moderna",
    location: "Petrolina",
    area: 800,
    price: 2500000,
    type: "imovel",
    description: "Casa térrea prática e sofisticada, com 3 suítes e ampla varanda gourmet.",
    features: ["Térrea", "Varanda Gourmet", "3 Suítes"],
    images: ["https://picsum.photos/seed/p6/800/600"],
    coordinates: { x: 46.5, y: 19.4 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "7",
    title: "Terreno Residencial A",
    location: "Petrolina",
    area: 800,
    price: 750000,
    type: "terreno",
    description: "Lote padrão pronto para construir, com toda infraestrutura.",
    features: ["Residencial", "Plano", "Pronto para construir"],
    images: ["https://picsum.photos/seed/p7/800/600"],
    coordinates: { x: 50.2, y: 19.4 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "8",
    title: "Terreno Residencial B",
    location: "Petrolina",
    area: 800,
    price: 750000,
    type: "terreno",
    description: "Lote em rua tranquila, ideal para família.",
    features: ["Rua tranquila", "Residencial"],
    images: ["https://picsum.photos/seed/p8/800/600"],
    coordinates: { x: 54.2, y: 19.3 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "9",
    title: "Terreno Residencial C",
    location: "Petrolina",
    area: 800,
    price: 750000,
    type: "terreno",
    description: "Oportunidade de investimento em área de valorização.",
    features: ["Investimento", "Residencial"],
    images: ["https://picsum.photos/seed/p9/800/600"],
    coordinates: { x: 58, y: 19.2 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "10",
    title: "Casa Minimalista",
    location: "Petrolina",
    area: 800,
    price: 3100000,
    type: "imovel",
    description: "Projeto minimalista premiado, com muita luz natural e integração com a natureza.",
    features: ["Minimalista", "Design", "Luz Natural"],
    images: ["https://picsum.photos/seed/p10/800/600"],
    coordinates: { x: 61.7, y: 19.2 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "11",
    title: "Terreno Residencial",
    location: "Petrolina",
    area: 800,
    price: 760000,
    type: "terreno",
    description: "Excelente topografia.",
    features: ["Plano", "Boa Topografia"],
    images: ["https://picsum.photos/seed/p11/800/600"],
    coordinates: { x: 65.3, y: 19.1 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "12",
    title: "Terreno Residencial",
    location: "Petrolina",
    area: 800,
    price: 760000,
    type: "terreno",
    description: "Próximo à área de lazer do condomínio.",
    features: ["Próximo ao clube", "Lazer"],
    images: ["https://picsum.photos/seed/p12/800/600"],
    coordinates: { x: 69.0, y: 18.9 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "13",
    title: "Terreno com Vista",
    location: "Petrolina",
    area: 850,
    price: 820000,
    type: "terreno",
    description: "Terreno com leve aclive e vista privilegiada do pôr do sol.",
    features: ["Vista", "Privacidade"],
    images: ["https://picsum.photos/seed/p13/800/600"],
    coordinates: { x: 72.7, y: 18.9 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "14",
    title: "Terreno Gigante",
    location: "Petrolina",
    area: 1100,
    price: 950000,
    type: "terreno",
    description: "Um dos maiores lotes do condomínio, espaço de sobra para seu projeto.",
    features: ["Amplo", "Exclusivo"],
    images: ["https://picsum.photos/seed/p14/800/600"],
    coordinates: { x: 76.4, y: 18.9 },
    contact: "contato@capitale.com",
    availability: true,
  },

  // Quadra B - Mista (Terrenos e Casas)
  {
    id: "15",
    title: "Terreno no Bosque",
    location: "Petrolina",
    area: 800,
    price: 780000,
    type: "terreno",
    description: "Fundo para o bosque, muita área verde e silêncio.",
    features: ["Área Verde", "Silêncio"],
    images: ["https://picsum.photos/seed/p15/800/600"],
    coordinates: { x: 42.8, y: 31.9 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "16",
    title: "Casa Duplex Luxo",
    location: "Petrolina",
    area: 800,
    price: 2800000,
    type: "imovel",
    description: "Duplex com 4 suítes, cinema privativo e adega.",
    features: ["Cinema", "Adega", "4 Suítes"],
    images: ["https://picsum.photos/seed/p16/800/600"],
    coordinates: { x: 42.8, y: 37.9 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "17",
    title: "Terreno Padrão",
    location: "Petrolina",
    area: 800,
    price: 720000,
    type: "terreno",
    description: "Excelente custo benefício no coração do condomínio.",
    features: ["Custo-benefício", "Central"],
    images: ["https://picsum.photos/seed/p17/800/600"],
    coordinates: { x: 46.3, y: 31.9 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "18",
    title: "Terreno Padrão",
    location: "Petrolina",
    area: 800,
    price: 720000,
    type: "terreno",
    description: "Lote plano, fácil construção.",
    features: ["Plano", "Fácil construção"],
    images: ["https://picsum.photos/seed/p18/800/600"],
    coordinates: { x: 46.3, y: 37.9 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "19",
    featured: true,
    title: "Smart Home Pronta",
    location: "Petrolina",
    area: 800,
    price: 3500000,
    type: "imovel",
    description: "Casa totalmente automatizada, sustentável e moderna. Venda de porteira fechada.",
    features: ["Automatizada", "Sustentável", "Mobiliada"],
    images: ["https://picsum.photos/seed/p19/800/600"],
    coordinates: { x: 54.6, y: 31.3 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "20",
    title: "Terreno",
    location: "Petrolina",
    area: 800,
    price: 700000,
    type: "terreno",
    description: "Lote regular.",
    features: ["Regular", "Bem localizado"],
    images: ["https://picsum.photos/seed/p20/800/600"],
    coordinates: { x: 58.3, y: 31.3 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "21",
    title: "Terreno",
    location: "Petrolina",
    area: 800,
    price: 700000,
    type: "terreno",
    description: "Lote regular.",
    features: ["Regular", "Bem localizado"],
    images: ["https://picsum.photos/seed/p21/800/600"],
    coordinates: { x: 62.0, y: 31.3 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "22",
    title: "Terreno",
    location: "Petrolina",
    area: 800,
    price: 700000,
    type: "terreno",
    description: "Lote regular.",
    features: ["Regular", "Bem localizado"],
    images: ["https://picsum.photos/seed/p22/800/600"],
    coordinates: { x: 65.4, y: 31.3 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "23",
    title: "Terreno",
    location: "Petrolina",
    area: 800,
    price: 700000,
    type: "terreno",
    description: "Lote regular.",
    features: ["Regular", "Bem localizado"],
    images: ["https://picsum.photos/seed/p23/800/600"],
    coordinates: { x: 69, y: 31.3 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "24",
    title: "Terreno de Fundo",
    location: "Petrolina",
    area: 900,
    price: 750000,
    type: "terreno",
    description: "Maior privacidade, sem vizinhos de fundo.",
    features: ["Privacidade", "Área Verde"],
    images: ["https://picsum.photos/seed/p24/800/600"],
    coordinates: { x: 72.6, y: 31.3 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "25",
    title: "Terreno de Fundo",
    location: "Petrolina",
    area: 900,
    price: 750000,
    type: "terreno",
    description: "Maior privacidade, sem vizinhos de fundo.",
    features: ["Privacidade", "Área Verde"],
    images: ["https://picsum.photos/seed/p25/800/600"],
    coordinates: { x: 76, y: 31.3 },
    contact: "contato@capitale.com",
    availability: true,
  },

  // Quadra C - Central
  {
    id: "26",
    title: "Terreno Central",
    location: "Petrolina",
    area: 800,
    price: 740000,
    type: "terreno",
    description: "Localização central no condomínio, perto de tudo.",
    features: ["Central", "Conviniência"],
    images: ["https://picsum.photos/seed/p26/800/600"],
    coordinates: { x: 54.7, y: 38.5 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "27",
    title: "Imóvel em Construção",
    location: "Petrolina",
    area: 800,
    price: 2100000,
    type: "imovel",
    description: "Oportunidade de assumir obra de casa de alto padrão e personalizar acabamentos.",
    features: ["Em obra", "Personalizável"],
    images: ["https://picsum.photos/seed/p27/800/600"],
    coordinates: { x: 58.4, y: 38.5 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "28",
    title: "Terreno",
    location: "Petrolina",
    area: 800,
    price: 740000,
    type: "terreno",
    description: "Lote excelente.",
    features: ["Plano"],
    images: ["https://picsum.photos/seed/p28/800/600"],
    coordinates: { x: 62, y: 38.5 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "29",
    title: "Terreno",
    location: "Petrolina",
    area: 800,
    price: 740000,
    type: "terreno",
    description: "Lote excelente.",
    features: ["Plano"],
    images: ["https://picsum.photos/seed/p29/800/600"],
    coordinates: { x: 65.5, y: 38.5 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "30",
    title: "Terreno",
    location: "Petrolina",
    area: 800,
    price: 740000,
    type: "terreno",
    description: "Lote excelente.",
    features: ["Plano"],
    images: ["https://picsum.photos/seed/p30/800/600"],
    coordinates: { x: 69.1, y: 38.5 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "31",
    title: "Terreno",
    location: "Petrolina",
    area: 800,
    price: 740000,
    type: "terreno",
    description: "Lote excelente.",
    features: ["Plano"],
    images: ["https://picsum.photos/seed/p31/800/600"],
    coordinates: { x: 72.7, y: 38.5 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "32",
    title: "Terreno de Esquina",
    location: "Petrolina",
    area: 920,
    price: 850000,
    type: "terreno",
    description: "Esquina ampla na parte alta.",
    features: ["Esquina", "Vista"],
    images: ["https://picsum.photos/seed/p32/800/600"],
    coordinates: { x: 76.3, y: 38.5 },
    contact: "contato@capitale.com",
    availability: true,
  },

  // Quadra D e E
  {
    id: "33",
    title: "Casa de Campo Moderna",
    location: "Petrolina",
    area: 1500,
    price: 3800000,
    type: "imovel",
    description: "Estilo fazenda moderna, terreno duplo, pomar e piscina natural.",
    features: ["Terreno Duplo", "Pomar", "Lajr"],
    images: ["https://picsum.photos/seed/p33/800/600"],
    coordinates: { x: 25.1, y: 55.3 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "34",
    title: "Terreno",
    location: "Petrolina",
    area: 800,
    price: 700000,
    type: "terreno",
    description: "Ótima oportunidade.",
    features: ["Oportunidade"],
    images: ["https://picsum.photos/seed/p34/800/600"],
    coordinates: { x: 28.7, y: 55.2 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "35",
    title: "Terreno",
    location: "Petrolina",
    area: 800,
    price: 700000,
    type: "terreno",
    description: "Ótima oportunidade.",
    features: ["Oportunidade"],
    images: ["https://picsum.photos/seed/p35/800/600"],
    coordinates: { x: 32.3, y: 55.2 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "36",
    title: "Terreno",
    location: "Petrolina",
    area: 800,
    price: 700000,
    type: "terreno",
    description: "Ótima oportunidade.",
    features: ["Oportunidade"],
    images: ["https://picsum.photos/seed/p36/800/600"],
    coordinates: { x: 35.8, y: 55.1 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "37",
    title: "Terreno",
    location: "Petrolina",
    area: 800,
    price: 700000,
    type: "terreno",
    description: "Ótima oportunidade.",
    features: ["Oportunidade"],
    images: ["https://picsum.photos/seed/p37/800/600"],
    coordinates: { x: 39.4, y: 54.9 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "38",
    title: "Terreno de Esquina",
    location: "Petrolina",
    area: 800,
    price: 750000,
    type: "terreno",
    description: "Lote de esquina.",
    features: ["Esquina"],
    images: ["https://picsum.photos/seed/p38/800/600"],
    coordinates: { x: 43.1, y: 54.8 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "39",
    title: "Terreno",
    location: "Petrolina",
    area: 800,
    price: 700000,
    type: "terreno",
    description: "Lote padrão.",
    features: ["Padrão"],
    images: ["https://picsum.photos/seed/p39/800/600"],
    coordinates: { x: 46.6, y: 54.7 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "40",
    title: "Imóvel Compacto Luxo",
    location: "Petrolina",
    area: 400,
    price: 1500000,
    type: "imovel",
    description: "Casa compacta de altíssimo padrão em meio lote.",
    features: ["Compacto", "Luxo"],
    images: ["https://picsum.photos/seed/p40/800/600"],
    coordinates: { x: 25.1, y: 62.6 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "41",
    title: "Terreno",
    location: "Petrolina",
    area: 800,
    price: 700000,
    type: "terreno",
    description: "Lote padrão.",
    features: ["Padrão"],
    images: ["https://picsum.photos/seed/p41/800/600"],
    coordinates: { x: 28.7, y: 62.5 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "42",
    title: "Terreno",
    location: "Petrolina",
    area: 800,
    price: 700000,
    type: "terreno",
    description: "Lote padrão.",
    features: ["Padrão"],
    images: ["https://picsum.photos/seed/p42/800/600"],
    coordinates: { x: 32.3, y: 62.4 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "43",
    title: "Terreno",
    location: "Petrolina",
    area: 800,
    price: 700000,
    type: "terreno",
    description: "Lote padrão.",
    features: ["Padrão"],
    images: ["https://picsum.photos/seed/p43/800/600"],
    coordinates: { x: 35.9, y: 62.3 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "44",
    title: "Terreno",
    location: "Petrolina",
    area: 800,
    price: 700000,
    type: "terreno",
    description: "Lote padrão.",
    features: ["Padrão"],
    images: ["https://picsum.photos/seed/p44/800/600"],
    coordinates: { x: 39.5, y: 62.2 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "45",
    title: "Terreno",
    location: "Petrolina",
    area: 800,
    price: 700000,
    type: "terreno",
    description: "Lote padrão.",
    features: ["Padrão"],
    images: ["https://picsum.photos/seed/p45/800/600"],
    coordinates: { x: 43.1, y: 62.1 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "46",
    title: "Terreno",
    location: "Petrolina",
    area: 800,
    price: 700000,
    type: "terreno",
    description: "Lote padrão.",
    features: ["Padrão"],
    images: ["https://picsum.photos/seed/p46/800/600"],
    coordinates: { x: 46.7, y: 62.0 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "47",
    title: "Terreno",
    location: "Petrolina",
    area: 800,
    price: 700000,
    type: "terreno",
    description: "Lote padrão.",
    features: ["Padrão"],
    images: ["https://picsum.photos/seed/p47/800/600"],
    coordinates: { x: 53.7, y: 55.5 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "48",
    title: "Terreno",
    location: "Petrolina",
    area: 800,
    price: 700000,
    type: "terreno",
    description: "Lote padrão.",
    features: ["Padrão"],
    images: ["https://picsum.photos/seed/p48/800/600"],
    coordinates: { x: 53.7, y: 63.3 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "49",
    title: "Terreno",
    location: "Petrolina",
    area: 800,
    price: 700000,
    type: "terreno",
    description: "Lote padrão.",
    features: ["Padrão"],
    images: ["https://picsum.photos/seed/p49/800/600"],
    coordinates: { x: 57.8, y: 55.5 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "50",
    title: "Terreno",
    location: "Petrolina",
    area: 800,
    price: 700000,
    type: "terreno",
    description: "Lote padrão.",
    features: ["Padrão"],
    images: ["https://picsum.photos/seed/p50/800/600"],
    coordinates: { x: 57.8, y: 63.2 },
    contact: "contato@capitale.com",
    availability: true,
  },

  // Quadra F - Final
  {
    id: "51",
    title: "Terreno",
    location: "Petrolina",
    area: 800,
    price: 700000,
    type: "terreno",
    description: "Lote com boa localização.",
    features: ["Tranquilo"],
    images: ["https://picsum.photos/seed/p51/800/600"],
    coordinates: { x: 23.7, y: 81.2 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "52",
    title: "Terreno",
    location: "Petrolina",
    area: 800,
    price: 700000,
    type: "terreno",
    description: "Lote com boa localização.",
    features: ["Tranquilo"],
    images: ["https://picsum.photos/seed/p52/800/600"],
    coordinates: { x: 27.5, y: 81.1 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "53",
    title: "Terreno",
    location: "Petrolina",
    area: 800,
    price: 700000,
    type: "terreno",
    description: "Lote com boa localização.",
    features: ["Tranquilo"],
    images: ["https://picsum.photos/seed/p53/800/600"],
    coordinates: { x: 31.4, y: 81.0 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "54",
    title: "Terreno",
    location: "Petrolina",
    area: 800,
    price: 700000,
    type: "terreno",
    description: "Lote com boa localização.",
    features: ["Tranquilo"],
    images: ["https://picsum.photos/seed/p54/800/600"],
    coordinates: { x: 35.2, y: 80.9 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "55",
    title: "Terreno",
    location: "Petrolina",
    area: 800,
    price: 700000,
    type: "terreno",
    description: "Lote com boa localização.",
    features: ["Tranquilo"],
    images: ["https://picsum.photos/seed/p55/800/600"],
    coordinates: { x: 39.1, y: 80.8 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "56",
    title: "Terreno",
    location: "Petrolina",
    area: 800,
    price: 700000,
    type: "terreno",
    description: "Lote com boa localização.",
    features: ["Tranquilo"],
    images: ["https://picsum.photos/seed/p56/800/600"],
    coordinates: { x: 54.7, y: 81.1 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "57",
    title: "Terreno",
    location: "Petrolina",
    area: 800,
    price: 700000,
    type: "terreno",
    description: "Lote com boa localização.",
    features: ["Tranquilo"],
    images: ["https://picsum.photos/seed/p57/800/600"],
    coordinates: { x: 58.4, y: 81.0 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "58",
    title: "Terreno",
    location: "Petrolina",
    area: 800,
    price: 700000,
    type: "terreno",
    description: "Lote com boa localização.",
    features: ["Tranquilo"],
    images: ["https://picsum.photos/seed/p58/800/600"],
    coordinates: { x: 62.2, y: 81 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "59",
    title: "Terreno",
    location: "Petrolina",
    area: 800,
    price: 700000,
    type: "terreno",
    description: "Lote com boa localização.",
    features: ["Tranquilo"],
    images: ["https://picsum.photos/seed/p59/800/600"],
    coordinates: { x: 65.9, y: 81 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "60",
    title: "Terreno",
    location: "Petrolina",
    area: 800,
    price: 700000,
    type: "terreno",
    description: "Lote com boa localização.",
    features: ["Tranquilo"],
    images: ["https://picsum.photos/seed/p60/800/600"],
    coordinates: { x: 69.8, y: 81 },
    contact: "contato@capitale.com",
    availability: true,
  },
  {
    id: "61",
    title: "Terreno",
    location: "Petrolina",
    area: 800,
    price: 700000,
    type: "terreno",
    description: "Lote com boa localização.",
    features: ["Tranquilo"],
    images: ["https://picsum.photos/seed/p61/800/600"],
    coordinates: { x: 73.6, y: 81 },
    contact: "contato@capitale.com",
    availability: true,
  },
];


